//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnumAnnotations.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnumAnnotations.Test.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizedStatus Fine Description.
        /// </summary>
        public static string LocalizedStatus_Fine_Description {
            get {
                return ResourceManager.GetString("LocalizedStatus_Fine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizedStatus Fine GroupName.
        /// </summary>
        public static string LocalizedStatus_Fine_GroupName {
            get {
                return ResourceManager.GetString("LocalizedStatus_Fine_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizedStatus Fine Name.
        /// </summary>
        public static string LocalizedStatus_Fine_Name {
            get {
                return ResourceManager.GetString("LocalizedStatus_Fine_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizedStatus Fine ShortName.
        /// </summary>
        public static string LocalizedStatus_Fine_ShortName {
            get {
                return ResourceManager.GetString("LocalizedStatus_Fine_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizedStatus Good Name.
        /// </summary>
        public static string LocalizedStatus_Good_Name {
            get {
                return ResourceManager.GetString("LocalizedStatus_Good_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizedStatus Ok Name.
        /// </summary>
        public static string LocalizedStatus_Ok_Name {
            get {
                return ResourceManager.GetString("LocalizedStatus_Ok_Name", resourceCulture);
            }
        }
    }
}
